update the "pbkdf2" package repo
adjust/gorails pull request #5
Opened 2017-09-24 02:02 UTC by gingerhot

update the "pbkdf2" package repo in README file

2017-09-25 09:47 UTC, andrewslotin requested changes
Thanks for your contribution!

2017-09-25 09:47 UTC, andrewslotin commented on session/README.md
> -go get -u code.google.com/p/go.crypto/pbkdf2
I believe these days this line is redundant, since the `go get` resolves and downloads package dependencies. Could you simply remove this line?

2017-09-25 12:02 UTC, gingerhot commented
Yes, you're right. I run into some errors just followed the steps blindly at first. Thanks for your reply.

2017-09-27 09:45 UTC, andrewslotin approved these changes
Great! Thanks again for your efforts. Hope you don't mind if I do a squash merge.

2017-09-27 09:45 UTC, merged

2017-09-27 11:04 UTC, gingerhot commented
Now maybe JWT is a better solution for authentication between different applications, but I think this package is still valuable for Go and Rails' interaction. I just want to have a try of it.  Thanks!

2017-09-27 12:38 UTC, andrewslotin commented
@gingerhot, there is plenty of Go libraries to handle JWT you might like to use. Feel free to go through [this blog post](http://big-elephants.com/2014-01/handling-rails-4-sessions-with-go/) to get a better idea on what this package does.

2017-09-27 13:13 UTC, gingerhot commented
This's really what I'm seeking for. Thank you very much!